title: "同洵洋行"                                 # Name of the site
default_lang: zh_TW                        # Default language for site (potentially used by theme)

author:
  name: chunchun hsieh                      # Default author name
  email: 'beer70881920@yahoo.com.tw'                 # Default author email
  copyright: "同洵商行"

contact:
  address:
    - line: "同洵洋行旗艦店"
    - line: "台灣桃園市中壢區民權路三段299號"
    - line: "(03)426-8448"

footer:
  contact_title: "聯絡資訊"

taxonomies: [category,tag]                  # Arbitrary list of taxonomy types

metadata:
  description: '同洵洋行創立於民國 88 年，從事各種菸酒飲料批發外送服務，在地服務多年，主要經營台酒、洋酒、紅酒、各式餐飲用啤酒、果汁、飲料批發、零售，年節禮盒及專業開店酒飲籌備規劃、喜慶筵席冷藏配送，客製化紅酒、活動派對用桶裝生啤酒、工商社團品酒會。'               # Site description

summary:
  enabled: true                             # enable or disable summary of page
  format: short                             # long = summary delimiter will be ignored; short = use the first occurrence of delimiter or size
  size: 300                                 # Maximum length of summary (characters)
  delimiter: ===                            # The summary delimiter

redirects:
#  '/redirect-test': '/'                    # Redirect test goes to home page
#  '/old/(.*)': '/new/$1'                   # Would redirect /old/my-page to /new/my-page

routes:
#  '/something/else': '/blog/sample-3'      # Alias for /blog/sample-3
#  '/new/(.*)': '/blog/$1'                  # Regex any /new/my-page URL to /blog/my-page Route

blog:
  route: '/blog'                            # Custom value added (accessible via site.blog.route)

#menu:                                      # Menu Example
#    - text: Source
#      icon: github
#      url: https://github.com/getgrav/grav
#    - icon: twitter
#      url: http://twitter.com/getgrav
